services:
  opendonita:
    build: .
    container_name: opendonita
    ports:
      - "80:80"
      - "20008:20008"
    volumes:
      - ./opendonita-data:/root/.opendonita
    restart: unless-stopped
